server:
  port: 8092 # 服务端口
wenjia:
  springdoc:
    scan: com.wenjia.coupon.controller
dubbo:
  protocol:
    port: 20882
rocketmq:
  producer:
    group: OrderGroup
  name-server: 192.168.145.128:9876