server:
  port: 8090 # 服务端口

wenjia:
  jwt:
    duration: 10000000000
    secret-key: wenjiawenjiawenjiawenjiawenjiawenjiawenjiawenjiawenjiawenjiawenjiawenjiawenjiawenjiawenjiawenjiawenjiawenjiawenjiawenjiawenjiawenjiawenjiawenjia;
  auth:
    exclude-paths:
      - /user/login
      - /user
      - /shop
      - /coupon
      - /coupon/stock
    may-paths:
      - /comment/page
      - /shop/page
